[requirement]
====
[%metadata]
identifier:: http://www.opengis.net/spec/uml2json/1.0/req/core/property-inline
statement:: The value type of a UML property SHALL be encoded as a JSON Schema constraint, as follows:
part:: If the value type of a UML property is an external type, and the JSON Schema definition of that external type is a simple JSON value type, i.e., "string", "number", "integer", or "boolean", then a "type" key SHALL be added to the JSON Schema definition of the property, with the simple JSON value type as value;
part:: Otherwise, a "$ref" key SHALL be added to the JSON Schema that constrains the property. The "$ref" value is a reference to the JSON Schema definition of the value type, within a particular definitions schema. The reference uses the "$id" of that schema (see <<jsonschema_req_core_definitionsschema>>) as a basis, and adds a fragment identifier to identify the definition of the type. If the JSON Schema definition of the value type contains an "$anchor" member (see <<jsonschema_req_core_types_classname>>), then the type name SHALL be used as fragment identifier. Otherwise, a JSON Pointer SHALL be created.

====