== Terms, definitions and abbreviated terms

=== Terms and definitions

==== linked data

_Linked data_ is the data format that supports the Semantic Web. The basic rules for linked data are defined as:

 * Use Uniform Resource Identifiers (URIs) to identify things;
 * Use HTTP URIs so that these things can be referred to and looked up ("dereferenced") by people and user agents;
 * Provide useful information about the thing when its URI is dereferenced, using standard formats such as RDF/XML; and
 * Include links to other, related URIs in the exposed data to improve discovery of other related information on the Web.

Source: https://www.w3.org/2001/sw/wiki/Semantic_Web_terminology#linked_data[W3C Semantic Web Wiki]

==== feature type

A _feature type_ as defined by the General Feature Model (see <<ref_iso19109>>). In an application schema, a _feature type_ is typically modeled using stereotype «FeatureType», or a stereotype that maps to that stereotype.

==== object type

An _object type_ is a standard class, instances are plain objects with identity. An _object type_ is not a _feature type_. In an application schema, an _object type_ has no stereotype, or has stereotype «Interface» or «Type», or has a stereotype that maps to one of these two options.

==== data type

As defined by <<ref_iso19103>>, section 6.10, a _data type_ is a class with stereotype «DataType» (or a stereotype that maps to that stereotype), which is a set of properties that lacks identity.

==== type with identity

A class that is a _feature type_ or an _object type_.


===	Abbreviated terms

API:: Application Programming Interface
ECMA:: European association for standardizing information and communication systems
GML:: Geography Markup Language
HTTP:: Hypertext Transfer Protocol
IETF:: Internet Engineering Task Force
INSPIRE:: Infrastructure for spatial information in Europe
IRI:: Internationalized Resource Identifier
ISO:: International Organization for Standardization
JSON:: JavaScript Object Notation
JSON-FG:: OGC Features and Geometries JSON
JSON-LD:: JSON for Linked Data
OCL:: Object Constraint Language
OGC:: Open Geospatial Consortium
OWL:: Web Ontology Language
RDF:: Resource Description Framework
RDFS:: RDF Schema
UGAS:: UML to GML Application Schema
UML:: Unified Modeling Language
URI:: Uniform Resource Identifier
URL:: Unform Resource Locator
W3C:: World Wide Web Consortium
XML:: Extensible Markup Language

/////

Note to self for future documents: You can find acronyms by generating the document as HTML, saving it as XHTML, and then running the following XQuery (for example in the oXygen XML editor, on the opened XHTML document):

let $acronyms :=
  for $text in //*[not(local-name() = ('script','style'))]/text()[fn:string-length() > 0]
  let $tokens := fn:tokenize($text,'\W')
  return
    for $token in $tokens
    return
    if(matches($token,'^[A-Z][A-Z0-9]+')) then $token else ()

return sort(distinct-values($acronyms))


You'll have to throw away false-positives but in general this has been useful.

/////