== Conventions

=== General

This section provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.


=== Identifiers

The normative provisions in this document are denoted by the URI

`http://www.opengis.net/spec/uml2json/1.0`

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.


=== JSON Schema URLs

This document uses the following base URLs for relevant JSON Schema files:

* GeoJSON: https://geojson.org/schema
* JSON-FG: https://beta.schemas.opengis.net/json-fg
* UML2JSON (defined by this specification): https://register.geostandaarden.nl/jsonschema/uml2json/0.1

NOTE: The JSON-FG schemas have not been published at https://beta.schemas.opengis.net/json-fg yet (as of Dec 12, 2022). The schema definition from this specification - see <<annex_uml2json_schema_definition>> - has been published at a temporary location. In both cases, the schema locations are expected to change during the OGC publication process.

// Using https://raw.githubusercontent.com/ (instead of, for example, beta.schemas) is a problem, since the content type of files served that way is "text/plain". JSON Schema validators typically ignore that media type, instead expecting application/json or application/schema+json. We should use different URLs.


=== Stereotype Names

Stereotype names within figures are written in lowerCamelCase, whereas stereotype names in the text are written in UpperCamelCase. In a future version of this document, all stereotype names should be written in UpperCamelCase, to follow UML 2 practice.
