[requirement]
====
[%metadata]
identifier:: http://www.opengis.net/spec/uml2json/1.0/req/geojson/primary-geometry

[.component,class=part]
--
If a feature type has a primary geometry property (identified following the rules in <<jsonschema_req_core_primary_geometry>>), and that property is directly owned by the feature type, and the JSON Schema implementation of the property type is one of the GeoJSON geometry schemas (i.e., one of the JSON Schema references listed in <<table_iso19107_types_geometry_member>>), then:

* In the JSON Schema definition of the feature type, the primary geometry property shall be encoded as a type restriction for the top-level "geometry" member. If the primary geometry property is optional, then the schema restriction for the "geometry" member shall define a choice - using the "oneOf" JSON Schema keyword - between a null value and the geometry schema definition for the value type of the geometry property. The primary geometry property shall not be encoded within the "properties" member.
* In instance data, the value of the primary geometry property shall be encoded within the top-level "geometry" member of the JSON object that represents the feature type.
--

====