[requirement]
====
[%metadata]
identifier:: http://www.opengis.net/spec/uml2json/1.0/req/jsonfg/primary-interval

[.component,class=part]
--
A UML property that is owned by a \<<featureType>> and that has tag "jsonPrimaryInterval" with value equal to, ignoring case, one of the allowed values "start", "end", or "period", shall not be encoded.

NOTE: The value types of UML properties that represent or constitute to the primary interval should be compatible with that use. For example, properties marked as primary interval start or end can have value type "Date", "DateTime", or "TM_Instant", whereas a property marked as primary interval period can have value type "TM_Period".
--

[.component,class=part]
--
A \<<featureType>> shall satisfy the following conditions:

* At most one of the direct properties has tag "jsonPrimaryInterval" = "period".
* At most one of the direct properties has tag "jsonPrimaryInterval" = "start".
* At most one of the direct properties has tag "jsonPrimaryInterval" = "end".
* The use of "period" and "start"/"end" are mutually exclusive within the direct properties of the \<<featureType>>: If one direct property has tag "jsonPrimaryInterval" = "period", none of the direct properties shall have tag "jsonPrimaryInterval" equal to "start" or "end". Likewise, if one direct property has tag "jsonPrimaryInterval" equal to "start" or "end", none of the direct properties shall have tag "jsonPrimaryInterval" = "period".
--

[.component,class=part]
--
In instance data, the value of properties that represent or constitute to the primary interval shall be encoded within the (JSON-FG) time/interval member of the JSON object that represents the \<<featureType>>.
--
====
